### Rename this file to config.yaml and change the corresponding values
### Possibly uncomment what you need

### If True then nothing will be posted to reddit when running 
debug: False

### Your reddit api key client_id and client_secret for the bot account
reddit_api:
    client_id: $your_reddit_api_client_id
    client_secret: $your_reddit_api_client_secret
    username: $your_reddit_bot_username
    password: $your_reddit_bot_password

subreddit:
    ### Example (do not write "/r/")
    ### name: geochallenges
    name: $subreddit_to_monitor

# User which will receive messages when there are errors
# if left out then no message will be sent
username_to_message_in_case_of_errors: LiquidProgrammer

# URL for server if self hosted
server_url: https://geostackr.brutenis.net/plots/

# Default values for all series if not supplied
defaults:
    top_count: 20
    top_plot_count: 5
    regex: \d{1,3}00

